#!/bin/sh

set -euo pipefail

# Initialization - load function handler
sourcecode=$(cat $LAMBDA_TASK_ROOT/$_HANDLER)

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event. The HTTP request will block until one is received
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  # Extract request ID by scraping response headers received above
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Execute the handler function from the script
  cd /opt/
  RESPONSE=$(sourcecode=$sourcecode event=$EVENT_DATA _HANDLER='zcl_handler.clas.abap' node runtime.js)

  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
done